default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.credentials.aiven[:DATABASE_NAME] %>
  username: <%= Rails.application.credentials.aiven[:DATABASE_USER] %>
  password: <%= Rails.application.credentials.aiven[:DATABASE_PASSWORD] %>
  port: <%= Rails.application.credentials.aiven[:DATABASE_PORT] || '5432' %>
  host: <%= Rails.application.credentials.aiven[:DATABASE_HOST] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
